-- local M = {
--   filetype = {
--     typescript = {
--       require("formatter.filetypes.typescript").prettier
--     },
--     javascript = {
--       require("formatter.filetypes.javascript").prettier
--     },
--     typescriptreact = {
--       require("formatter.filetypes.typescriptreact").prettier
--     },
--     javascriptreact = {
--       require("formatter.filetypes.javascriptreact").prettier
--     },
--     ["*"] = {
--       require("formatter.filetypes.any").remove_trailing_whitespace
--     }
--   }
-- }
--
-- return M
