notARepository: 'quit'
promptToReturnFromSubprocess: false
git:
  localBranchSortOrder: recency
  log:
    showGraph: always
    showWholeGraph: true
  overrideGpg: true
  pagers:
    - pager: delta --paging=never --tabs=2 -n --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  editPreset: nvim
gui:
  tabWidth: 2
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
    selectedLineBgColor:
      - "#0e0e0e"
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: '3'
keybinding:
  files:
    commitChangesWithoutHook: <disabled>
customCommands:
  - key: w
    prompts:
      - type: input
        title: Commit summary
        initialValue: ''
    description: Commit changes without pre-commit hook
    command: git commit -n -m '{{index .PromptResponses 0}}'
    context: files
