# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    border_size = 2
    col.active_border = rgba(ff5555ff)
    col.inactive_border = rgba(000000ff)

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Disable Hyprland blur for a solid, non-glass look
    blur {
        enabled = false
    }

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# Force all normal windows fully opaque
windowrule = opacity 1 1, match:class .*

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
